[mgr]
show_hidden = true

[manager]
ratio           = [1, 4, 3]
linemode        = "size"
sort_by         = "natural"
sort_dir_first  = true
show_hidden     = false
show_symlink    = true
scrolloff       = 6

[preview]
wrap            = "no"
image           = true
image_quality   = 90

[opener]
zed = [
    { run = 'zed "$@"', desc = "Zed", orphan = true, for = "unix" },
]
