include dank-tabs.conf
include dank-theme.conf

# Basic
scrollback_lines 5000
shell /usr/bin/zsh

# UX
confirm_os_window_close 0
enable_audio_bell no

# Style
cursor_trail 500
font_size 10.0 
window_padding_width 25
cursor_trail 1
background_opacity 0.3
hide_window_decorations yes

# Tabs
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# BEGIN_KITTY_FONTS
font_family      family='CaskaydiaCove Nerd Font Mono' postscript_name=CaskaydiaCoveNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
